version: '3.9'
services:
  backend:
    build: datarecovery-backend
    container_name: datarecovery-backend
    image: datarecovery-backend:0.0.1
    expose:
      - "8088"
    env_file:
      - jungbauer.env
    depends_on:
      - db
  frontend:
    build: datarecovery-frontend
    image: datarecovery-frontend:0.0.1
    container_name: datarecovery-frontend
    depends_on:
      - backend
    command: [nginx-debug, '-g', 'daemon off;']
    env_file:
      - jungbauer.env
    ports:
    - "80:80"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=&fC6Pt4THH4^!x6@r8wR&Yz
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - jungbauer.env
