version: "3.9"
services:
  backend:
    build: datarecovery-backend
    container_name: datarecovery-backend
    image: datarecovery-backend:0.0.1
    expose:
      - "8088"
    env_file:
      - jungbauer.env
    depends_on:
      - db
  frontend:
    build: datarecovery-frontend
    image: datarecovery-frontend:0.0.1
    container_name: datarecovery-frontend
    command: [nginx-debug, '-g', 'daemon off;']
    environment:
      VIRTUAL_HOST: www.jungbauerdatenrettung.de #Your Domain here
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: www.jungbauerdatenrettung.de #Your Domain here
      LETSENCRYPT_EMAIL: info@jungbauerdatenrettung.de #Your Email
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - jungbauer.env

  proxy:
    image: jwilder/nginx-proxy
    restart: always
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /root/proxy/volumes/jwilder-proxy/certs:/etc/nginx/certs:ro
      - /root/proxy/volumes/jwilder-proxy/config:/etc/nginx/conf.d
      - /root/proxy/volumes/jwilder-proxy/dhparam:/etc/nginx/dhparam
      - /root/proxy/volumes/jwilder-proxy/vhosts:/etc/nginx/vhost.d
      - /root/proxy/volumes/jwilder-proxy/html:/usr/share/nginx/html
  # LetsEncrypt plugin, which generates certificates
  nginx-letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /root/proxy/volumes/jwilder-proxy/certs:/etc/nginx/certs
      - /root/proxy/volumes/jwilder-proxy/vhosts:/etc/nginx/vhost.d
      - /root/proxy/volumes/jwilder-proxy/html:/usr/share/nginx/html
      - /root/proxy/volumes/jwilder-proxy/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: thaiminater@outlook.com
    depends_on:
      - proxy
