server:
  port: 8088
spring:
  datasource:
    url: jdbc:h2:file:./data/datarecovery;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: thomas.schuehly.mibi
    password: ${MAIL_SENDER_PASSWORD}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
