name: Docker Build and Push 
on:
  push:
    branches: [ jungbauer_deploy ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker build
        run: | 
          docker build ./datarecovery-backend -t ghcr.io/tschuehly/datarecovery/datarecovery-backend-jungbauer:latest
          docker build ./datarecovery-frontend -t ghcr.io/tschuehly/datarecovery/datarecovery-frontend-jungbauer:latest
      - name: docker push
        run: |
          docker login ghcr.io -u ${GITHUB_REPOSITORY_OWNER} -p ${GITHUB_TOKEN}
          docker push ghcr.io/tschuehly/datarecovery/datarecovery-frontend-jungbauer:latest
          docker push ghcr.io/tschuehly/datarecovery/datarecovery-backend-jungbauer:latest
